version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=tech_news
      - POSTGRES_USER=tech_news_user
      - POSTGRES_PASSWORD=tech_news_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/posgresql/data
volumes:
  db-data: